apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Igor-Solovko/argo_poc.git
    targetRevision: HEAD
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true #will be used if namespace =! defalut 
    
    automated:
      selfHeal: true
      prune: true